prompt_order=["hostname","character","directory","git_branch","git_status"]
add_newline = false

[character]
symbol = "➜"
error_symbol = "✗"
use_symbol_for_status = true
style_success = "yellow"
style_failure = "yellow"

[directory]
truncation_length = 1
prefix = ""
style = "bold #0BA5A9"

[git_branch]
symbol = ""
style = "bold #D82B69"

[hostname]
ssh_only = false
prefix = "@"
style = "bold red"

[rust]
prefix = ""
symbol = "🦀"
