format = """\
        $hostname\
        $character\
        $cmd_duration\
        $directory\
        $git_branch\
        $git_status\
        """
add_newline = false

[character]
success_symbol = "[➜](yellow)"
error_symbol = "[✗](yellow)"
vicmd_symbol = "[](yellow)"
format=" $symbol "

[directory]
truncation_length = 1
format = "[$path](cyan) "

[git_branch]
symbol = ""
format = "[$symbol$branch](bold #D82B69) "

[hostname]
ssh_only = false
format = "[@$hostname](red)"

[rust]
format = "$symbol "
